# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    env:
      XCODE_VERSION: 'Xcode_16.2'

    runs-on: macos-15

    steps:
    - uses: actions/checkout@v4
    - name: Select Xcode
      run: sudo xcode-select -s "/Applications/$XCODE_VERSION.app"
    - name: Install SwiftLint
      run: brew install swiftlint
    - name: Lint
      run: swiftlint lint --config .swiftlint.yml
    # iOS build (default)
    - name: Build iOS
      run:  xcodebuild -scheme VimViewer -configuration Debug CODE_SIGNING_ALLOWED=NO -destination "generic/platform=iOS"
    # macOS build (if the PR has the label of 'os:macOS' applied)
    - name: Build macOS
      if: ${{ contains(github.event.pull_request.labels.*.name, 'macOS') }}
      run:  xcodebuild -scheme VimViewer -configuration Debug CODE_SIGNING_ALLOWED=NO -destination "generic/platform=macOS"
    # visionOS build (if the PR has the label of 'os:visionOS' applied)
    - name: Build visionOS
      if: ${{ contains(github.event.pull_request.labels.*.name, 'visionOS') }}
      run:  xcodebuild -scheme VimViewer -configuration Debug CODE_SIGNING_ALLOWED=NO -destination "generic/platform=visionOS"
